### ISSUE TITLE
Grid ground pours cannot be manufactured at JLCPCB

### ISSUE THREAD

**Issue by piit79** [megamind4089/STeMCell#2]
Hey, thanks for such a great open-source project! I just ordered a batch of STeMCells at JLCPCB and wanted to mention that they came back saying the resolution of the "grid" in the ground pours is higher than they can manufacture and had to change it to standard solid pours.

I had to find a replacement USB-C socket as the one in the BOM had a stock shortage, and is now also marked as "not recommended for new designs". The one I used has part number C963372.
EDIT: The above USB-C connector was **not the best choice** - it is not fully mid-mounted but rather slightly raised above the bottom of the PCB.

Also, the "corrected" cpl / pos CSV file worked, but all the positions seemed to be off by more or less the same offset and had to be corrected manually. I will try to get the corrected file and submit a PR.

**Comment by megamind4089** [comment]
Hi @piit79 

Thanks for nice words. Apologies for late reply. I missed this issue.
I have printed/assembled all versions of STeMCell with JLC only, and they printed it properly. I guess its again depend on the panel reviewers.
Some of them are allowing to print it with "grid" ground pour.
I will try to remove it in next major version.

As far as the parts, USB connectors are not fully available all the time. So bear with the burden of searching and changing it while ordering.

Feel free to submit PR for corrected POS file. Will merge it

**Comment by megamind4089** [comment]
Both the issues have been fixed now with v2.0.0.
The following render is directly from JLCPCB, and all parts are positioned correctly.

Will close this issue, if you do not have further comments

<p align="center">
  <img alt="front" src="https://user-images.githubusercontent.com/68985133/183408196-e8827b5c-3602-4dc6-b5d7-0847aceec2b7.png" width="45%">
&nbsp; &nbsp; &nbsp; &nbsp;
  <img alt="back" src="https://user-images.githubusercontent.com/68985133/183408213-4823dc24-2b18-4d28-9b3c-edf1a9320251.png" width="45%">
</p>

**Comment by piit79** [comment]
That's awesome, thank you!

**Comment by wantei** [comment]
Amazing work being done here!
